name: Update README and Pacman Graph

on:
  schedule: 
    - cron: "0 */3 * * *"
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  update_readme_and_graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate README
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/data \
            -w /data \
            -e GITHUB_TOKEN=${{ secrets.PERSONAL_GITHUB_TOKEN }} \
            cyteon/markscribe \
            -write README.md templates/readme.tpl

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update README and Pacman graph
          branch: main
          commit_user_name: markscribe
          commit_user_email: actions@github.com
          commit_author: markscribe <actions@github.com>
