name: Update README and Pacman Graph

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update_readme_and_graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Generate README
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/data \
            -w /data \
            -e GITHUB_TOKEN=${{ secrets.PERSONAL_GITHUB_TOKEN }} \
            cyteon/markscribe \
            -write README.md templates/readme.tpl

      - name: Generate pacman contribution graphs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Commit and push changes
        run: |
          git config user.name "Markscribe Bot"
          git config user.email "actions@github.com"

          # Only commit if there are changes
          if ! git diff --quiet; then
            git add .
            git commit -m "Update README and Pacman graph"
            git push origin main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
