name: Update README, Pacman Graph, and Stats Card

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update_readme_and_graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Generate README
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/data \
            -w /data \
            -e GITHUB_TOKEN=${{ secrets.PERSONAL_GITHUB_TOKEN }} \
            cyteon/markscribe \
            -write README.md templates/readme.tpl

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pacman contribution graphs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          if ! git diff --quiet; then
            git add README.md profile/*.svg **/*.svg
            git commit -m "Update README, stats card, and Pacman graph"
            git push origin main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
