name: Update README, Pacman Graph, and Stats Card

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update_readme_and_graph:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Generate README
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/data \
            -w /data \
            -e GITHUB_TOKEN=${{ secrets.PERSONAL_GITHUB_TOKEN }} \
            cyteon/markscribe \
            -write README.md templates/readme.tpl

      - name: Generate pacman contribution graphs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          if ! git diff --quiet; then
            git add README.md **/*.svg
            git commit -m "Update README and Pacman graph"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
